#ifndef __DECATHLON_DARTBOARD_H
#define __DECATHLON_DARTBOARD_H

#include "dartboard.h"

#define N_ROWS   7
#define N_COLS   10
#define ROWS_OFF 1 // First row pin (offset)
#define COLS_OFF 0 // First col pin (offset)

static int map_numbers[N_ROWS][N_COLS] = {
	{N9, N12, N5, N20, N10, N6, N13, N4, N18, N1},
	{N9, N12, N5, N20, N10, N6, N13, N4, N18, N1},
	{N9, N12, N5, N20, N10, N6, N13, N4, N18, N1},
	{BULL, BULL, N_INVALID, N_INVALID, N_INVALID, N_INVALID, N_INVALID, N_INVALID, N_INVALID, N_INVALID},
	{N14, N11, N8, N16, N15, N2, N17, N3, N19, N7},
	{N14, N11, N8, N16, N15, N2, N17, N3, N19, N7},
	{N14, N11, N8, N16, N15, N2, N17, N3, N19, N7},
};

static int map_zones[N_ROWS][N_COLS] = {
	{TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE},
	{DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE},
	{SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT},
	{DOUBLE, SINGLE_EXT, Z_INVALID, Z_INVALID, Z_INVALID, Z_INVALID, Z_INVALID, Z_INVALID, Z_INVALID, Z_INVALID},
	{SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT, SINGLE_EXT},
	{DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE},
	{TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE, TRIPLE},
};

#endif // __DECATHLON_DARTBOARD_H
